source:
    ./src
plugins:
    - jekyll-minifier
    - jekyll-postcss
collections:
    writings:
        output: true
        permalink: /:collection/:name
defaults:
    - scope:
        type: "writings"
      values:
        layout: "writings"
future: true
theme: null
url: "https://u1trav101.net"
jekyll-minifier:
    exclude: "*.css"
    compress_css: false
    uglifier_args:
        harmony: true